### ISSUE TITLE
Building opus 1.3 results in libopus.so.0.7.0

### ISSUE THREAD

**Issue by trampster** [xiph/opus#114]
I'm not a c developer so may have done something wrong..

1. Downloaded source from http://opus-codec.org/release/stable/2018/10/18/libopus-1_3.html
2. Extracted to folder.
3. Read readme and guessed that the distribution tarball instructions not the git instructions are relevant.
4. Ran ./configure
5. Ran make

Couldn't find .so file, but eventually found it in .libs as libopus.so, which was a simlink to libopus.so.0.7.0 this was a bit confusing as I was expected version 1.3

Sorry if this is just me not understanding what to do.

**Comment by trampster** [comment]
Having looked a bit deeper I see that the the version in ubuntu 18.04. is 1.12 but the file is libopus.so.0.5.2

I guess the package / public version number is intended to be different from the binary version number on the .so files.

Is there somewhere public that examples the mapping between .so/lib version number and the public/package version number.

Or at least what the version number policy is?

**Comment by rillian** [comment]
Right, the number after the .so extension in the filename is for [determining binary compatibility](https://autotools.io/libtool/version.html)  and is completely independent of the release version number. You can call `opus_get_version_string()` on your compiled library to get the release version.

The soname versioning, as it's called, is set [here](https://github.com/xiph/opus/blob/master/configure.ac#L24-L27). I'm not aware of a list mapping those to release versions; you'd have to go back through the commit history (e.g. check that file for every release tag) to find that information. The intention is to just use `opus_get_version_string` and to leave the details of the so versioning to the linker.

**Comment by trampster** [comment]
Thanks for the explanation.

**Comment by rillian** [comment]
You're welcome! :)
