### ISSUE TITLE
Script 'update_version' incorrectly identifies latest version...

### ISSUE THREAD

**Issue by bidafiwoc** [xiph/opus#12]
I'm using recent clone of git repository (HEAD of master branch at commit 99aaff599e77cda8d6d709288a087d0fcdaef13d), and I'm noticing some spurious behavior with versions and tags.  When I go through typical autoconf procedure (ie, running `./autogen.sh` to create `configure`), I note that `configure.ac` calls the `update_version` script.  Looking at that script, I see the following lines:
```
# We run `git status` before describe here to ensure that we don't get a false
# -dirty from files that have been touched but are not actually altered in the
# working dir.
GIT_VERSION=$(cd "$SRCDIR" && git status > /dev/null 2>&1 \
                           && git describe --tags --match 'v*' --dirty 2> /dev/null)
GIT_VERSION=${GIT_VERSION#v}
```
On my system (Debian Jessie [amd64], with git version 2.1.4), the output of this git call is:
```
v1.1.1-rc-91-g99aaff59
```
But that seems a bit ridiculous, as the output of `git tag | tail -1` is:
```
v1.1.2
```
I suspect there's some issue with the tagging of v1.1.2, also recognizable in that the v1.1.2 tag does NOT show up if I execute `git log --decorate=full`, but does show up if I execute `git log --decorate=full --tags`.  The v1.1.1-rc tag shows up in both cases.  I've read about [some weird corner cases with tagging on StackOverflow](http://stackoverflow.com/questions/4211604/show-all-tags-in-git-log), maybe this is related.

Regardless, it results in the wrong version information being embedded in the `autoconf` configured output, which I don't think is a good thing.

I actually discovered this while hunting for another, related bug in versioning, but I'll report that separately.

**Comment by rillian** [comment]
Yeah, this is unfortunate. The 1.1.1, 1.1.2 release was tagged on a branch which wasn't merged back into master, so you get stale-looking (but technically correct) git version output. It's a common issue with taking versioning from git commit info, but it should make sense if you build from the release branches.
