### ISSUE TITLE
CMake Improvements - Build and install documentation

### ISSUE THREAD

**Issue by xnorpx** [xiph/opus#120]
From: @mark4o 

It appears that the documentation is not being built or installed by the
cmake build; the autotools build builds and installs the documentation
by default unless configured with --disable-doc.

**Comment by willson-chen** [comment]
Under the autotools way:
```
opus/doc # make
make: Nothing to be done for 'all'
opus/doc # make install
make[1]: Nothing to be done for 'install-exec-am'
make[1]: Nothing to be done for 'install-data-am'
```
It seems that no doc is generated by make. And nothing will be installed.

**Comment by xnorpx** [comment]
https://vicrucann.github.io/tutorials/quick-cmake-doxygen/

**Comment by xnorpx** [comment]
Moved issue to xiph closing here: https://gitlab.xiph.org/xiph/opus/-/issues/2333
