### ISSUE TITLE
CMake Improvements - Fix Linux ARM build warnings

### ISSUE THREAD

**Issue by xnorpx** [xiph/opus#127]
From @mark4o 

I tried a cmake build on a non-x86 Linux host but encountered numerous
warnings of the form:
  celt/float_cast.h:129:10: warning: #warning "Don't have the functions
lrint() and lrintf ()." [-Wcpp]
  celt/float_cast.h:130:10: warning: #warning "Replacing these functions
with a standard C cast." [-Wcpp]

The host does have both the lrint and lrintf functions; the problem is
that cmake did not define either HAVE_LRINT or HAVE_LRINTF.

**Comment by xnorpx** [comment]
This will be resolved in next patch update

**Comment by realnc** [comment]
> This will be resolved in next patch update

Will there ever be a next patch update? :stuck_out_tongue:

**Comment by xnorpx** [comment]
Not sure I don’t have commit access and getting maintainers to review CMake patches is hard and time consuming as the interest for CMake is low, especially on non windows platforms. But you might have more time to get patches through on Gitlab than me.

**Comment by xnorpx** [comment]
a change for this has been pushed
