### ISSUE TITLE
opus_buildtype.cmake is missing in opus 1.3.1 tar

### ISSUE THREAD

**Issue by mnpaunov** [xiph/opus#129]
@xnorpx
In the newest release (opus-1.3.1) the CMakeLists.txt is looking for "opus_buildtype.cmake" which is missing from the distributed tar, but is present in the git repo.

**Comment by xnorpx** [comment]
Thanks @mnpaunov I added a pull request for @jmvalin to approve.

**Comment by willson-chen** [comment]
I reproduced it by type `cmake .`. The error information as follow:
```
CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    opus_buildtype.cmake
```
And no makefile was generated.

**Comment by rillian** [comment]
Right. I merged the patch in 86e5f5ea56, but didn't mark this issue as resolved. This is just waiting for a new release.

Sounds like we need to add a cmake build to `make distcheck`!

**Comment by willson-chen** [comment]
@rillian Wow, nice to see you here

**Comment by aberaud** [comment]
No release since 2019 and the problem is still there :)

**Comment by JarvisChu** [comment]
I fixed this problem by copy the  "opus_buildtype.cmake"  file from https://github.com/bincrafters/conan-opus/blob/stable/1.3.1/opus_buildtype.cmake

**Comment by markand** [comment]
Any chance we get a new release just for that fix? e.g. 1.3.2. This breaks Windows builds.
