### ISSUE TITLE
Script 'update_version' is missing from downloadable tarball / zip-file, even when present in repo...

### ISSUE THREAD

**Issue by bidafiwoc** [xiph/opus#13]
The `update_version` script is inexplicably missing from the downloadable tarball (or zip-file) of the last released version (v1.1.2), even when it is present in the repository --- I'm confused / surprised that this is happening, but find it easily reproducible.  Per my other recent issue report (#12), I'm running Debian Jessie (amd64) with git version 2.1.4.  I download the gzip'd tarball from GitHub as follows:

```
wget https://github.com/xiph/opus/archive/v1.1.2.tar.gz
tar xzvf v1.1.2.tar.gz
```

I clone the repo at the same tag as follows:

```
git clone http://github.com/xiph/opus.git
git checkout tags/v1.1.2
```

I then compare the list of files between the two (via successive `find -type f | sort -k9`), and find that v1.1.2 from the tarball is missing `update_version` (as well as the `.git` directory, which is obviously to be expected), even though it is present in v1.1.2 tag via git-clone...  Weird (at least to me).  Please see the output from `diff FileList.FromTarBall FileList.FromGitClone`:

```
120a121,144
> ./.gitattributes
> ./.git/config
> ./.git/description
> ./.git/HEAD
> ./.git/hooks/applypatch-msg.sample
> ./.git/hooks/commit-msg.sample
> ./.git/hooks/post-update.sample
> ./.git/hooks/pre-applypatch.sample
> ./.git/hooks/pre-commit.sample
> ./.git/hooks/prepare-commit-msg.sample
> ./.git/hooks/pre-push.sample
> ./.git/hooks/pre-rebase.sample
> ./.git/hooks/update.sample
> ./.gitignore
> ./.git/index
> ./.git/info/exclude
> ./.git/logs/HEAD
> ./.git/logs/refs/heads/master
> ./.git/logs/refs/remotes/origin/HEAD
> ./.git/objects/pack/pack-80603375c3f957ac617456b999e2240d6ff6d204.idx
> ./.git/objects/pack/pack-80603375c3f957ac617456b999e2240d6ff6d204.pack
> ./.git/packed-refs
> ./.git/refs/heads/master
> ./.git/refs/remotes/origin/HEAD
344a369
> ./update_version
```

I'm sure you can imagine that there are all kinds of follow-on effects of this missing `update_version` script.  The `configure.ac` script ends up selecting `unknown` for the version information, which then gets embedded in the `pkg-config` files, and (at least via my method of configuring `opus-tools` via `PKG_CONFIG_PATH` environmental variables), causing the `opus-tools` configure script to fail (as `libopus` no longer passes the version check, even though it definitely is the most recent version).

Thoughts on how to correct this, please?  I'd presume it's either an issue with the v1.1.2 tag (perhaps related to issue #12 I just submitted), or maybe there's some script that makes the tarballs that is not properly including this `update_version` file (though I grep'd throughout the source-tree and couldn't find anything obvious).

Thanks for all your help, as well as a great bunch of libraries (in opus/ogg)!

**Comment by bidafiwoc** [comment]
Continuing to investigate this... This bug is not only confined to tarball releases of tagged versions, but is also present in the tarball release of the current commit when downloaded from github.com:
```
wget https://github.com/xiph/opus/archive/master.tar.gz
tar xvzf master.tar.gz
```
Invoking `autogen.sh` on resulting directory will result in a `configure` file that defines environmental variable `VERSION` as `unknown`.  External xiph packages, such as `opus-tools` which rely upon version checks of `libopus` continue to therefore fail `autoconf` checks.

 Bug is not present when entire git repo is cloned from github (for reasons explained in above post).

Above tests are on system with git version 2.1.4, autoconf 2.69, automake 1.14.1, and libtoolize 2.4.2 (in other words, a standard Debian stable [Jessie] system).

Appreciate your input.  Incidentally, I can come up with patches that fix this, through modifications in `configure.ac`, but perhaps they would come at the expense of other corner cases in the logic of the `libopus` build system.  Therefore, I thought it best to get your input prior to implementing them, and filing a PR.

**Comment by rillian** [comment]
Github's auto-tarball feature doesn't properly support GNU autotools. What's supposed to happen is that release tarballs are created with `make distcheck` which will build the configure script and Makefile templates and pickle in the git version. Github's tag-based tarballs are just the raw contents of the repository, and the configure script assumes in that case it will have the repo history to query for a version string. I'm not sure why github doesn't include `update-version` in their tarballs. If you can figure out how to change that, or turn off the tarballs, I'd be happy to do that.

I think it's possible to upload builds to github somehow. If we'd mirrorred the official release tarballs (e.g. https://archive.mozilla.org/pub/opus/opus-1.1.2.tar.gz) on github would that have helped? Would you want an equilvalent tarball of the master branch?

**Comment by mark4o** [comment]
I think that `update_version` is excluded by `git archive` because it is listed as `export-ignore` in `.gitattributes`.

**Comment by rillian** [comment]
Aha, thanks!

I think just removing the export-ignore attribute doesn't help, since configure falls back to 'unknown' without it. Perhaps the question is whether we want to restore the fallback to a hard-coded version in version.mk like the windows build uses for this, or rely on `make dist` only to get this right.

**Comment by jmvalin** [comment]
So anything reasonable we can do here, or should we close this?

**Comment by wiiaboo** [comment]
It was decided somewhere (IRC?) that git archives wouldn't be supported, since there's no .git directory to obtain the versions from.
