### ISSUE TITLE
Incorrect 32bit version of MULT16_32_Q16

### ISSUE THREAD

**Issue by VitalyGu** [xiph/opus#158]
Hello , in file [celt/fixed_generic.h](https://github.com/xiph/opus/blob/master/celt/fixed_generic.h)
on line 43 
`
#define MULT16_32_Q16(a,b) ADD32(MULT16_16((a),SHR((b),16)), SHR(MULT16_16SU((a),((b)&0x0000ffff)),16))
`
incorrect when b < 0 and a > 0.
On this condition  SHR(MULT16_16SU((a),((b)&0x0000ffff))   positive,  but have to  be negative.

**Comment by jmvalin** [comment]
I don't see what you think is wrong here. The second operand to MULT16_16SU() is ((b)&0x0000ffff) -- it's an unsigned value, so it's *always* positive.

**Comment by VitalyGu** [comment]
Example in decimal:
a=10 b= -1080
a*b= 10*(-1080)= -10*100 -10*8
but in MULT16_32_Q16   10*(-1080)= -10*100 +10*8, because second part always positive;

**Comment by jmvalin** [comment]
I think you should revise how two's complement arithmetic works. With the shift and mask, -1080 wouldn't get broken down into -1000 and -80, but rather into -1100 and +20.

**Comment by VitalyGu** [comment]
You are ABSOLUTELY right.
