### ISSUE TITLE
Opus Decoder does not produce a good output.

### ISSUE THREAD

**Issue by MohseniBigBoy** [xiph/opus#161]
I use Opus decoder to decode obtained Opus packets from RTP packets. RTP packet parser works properly, but Opus decoder generate bad output.

The output has very small pulses at every seconds and between them has no signal, but its duration is correct.

Here is my code.

```
#define FRAME_SIZE 960
#define SAMPLE_RATE 16000
#define CHANNELS 2
#define MAX_PACKET_SIZE (3*1276)
//#define MAX_FRAME_SIZE 6*960
#define MAX_FRAME_SIZE 2880

ELA::OpusDecoder::OpusDecoder(const opus_int32 sampling_rate, const int number_of_channels)
{
    decoder = opus_decoder_create(sampling_rate, number_of_channels, &err);
    if (err<0)
    {
        fprintf(stderr, "failed to create decoder: %s\n", opus_strerror(err));
        exit(EXIT_FAILURE);
    }
}

ELA::OpusDecoder::~OpusDecoder()
{
    opus_decoder_destroy(decoder);
}

void ELA::OpusDecoder::decode(const AudioBuffer& input, AudioBufferRef& output, char* scratch)
{
    const AudioBufferDetails& details = input.details;
    char* in_buff_ptr = input.buffer;
    int bytes_remaining = details.bytes_count;
    char*  out_buff_ptr = scratch;
    uint32_t out_buff_size = 0;
    unsigned char cbits[MAX_FRAME_SIZE];

    memcpy(cbits, in_buff_ptr, bytes_remaining);

    int number_of_samples_in_packet = opus_decoder_get_nb_samples(decoder,cbits, MAX_FRAME_SIZE);
    int packet_channels = opus_packet_get_nb_channels(cbits);
    int packet_frame_count = opus_packet_get_nb_frames(cbits, MAX_FRAME_SIZE);
    int packet_samples = opus_packet_get_nb_samples(cbits, MAX_FRAME_SIZE, SAMPLE_RATE);
    int packet_bandwidth= opus_packet_get_bandwidth(cbits);
    int packet_sample_per_frame = opus_packet_get_samples_per_frame(cbits, SAMPLE_RATE);

    printf("\n %d  number_of_samples_in_packet", number_of_samples_in_packet);
    printf("\n %d  packet_channels", packet_channels);
    printf("\n %d  packet_frame_count", packet_frame_count);
    printf("\n %d  packet_samples", packet_samples);
    printf("\n %d  packet_bandwidth", packet_bandwidth);
    printf("\n %d  packet_sample_per_frame", packet_sample_per_frame);

    frame_size = opus_decode(decoder, cbits, bytes_remaining, (opus_int16*)out_buff_ptr, MAX_FRAME_SIZE, 0);

    if (err<0)
    {
        fprintf(stderr, "\ndecoder failed: %s\n", opus_strerror(err));
        exit(EXIT_FAILURE);
    }
    else
    {
        out_buff_ptr += bytes_remaining;
        out_buff_size += bytes_remaining;
    }

    save_output_audio_buffer(out_buff_size, scratch);
}
```

**Comment by rillian** [comment]
> ``` memcpy(cbits, in_buff_ptr, bytes_remaining);```

You should check `bytes_remaining` here against the length of the `cbits` array.

It's hard to tell exactly what's wrong, but there seems to be some confusion between compressed packet length (bytes) and decoded pcm audio length (samples per channel). You used `bytes_remaining` and `MAX_PACKET_SIZE` for both, but these shouldn't be the same number in general.

You should pass the packet length obtained from the RTP parser as the third argument to `opus_decode` and advance the output buffer pointer by the the output of `opus_packet_get_nb_samples` for each decoded packet. Try cleaning up that and see if the issue becomes apparent.

I also don't see any logic for handling packet loss. Do you have a jitter buffer in your RTP to handle out-of-order delivery? Those two things aren't necessary for local tests, but are important when using the WAN or other congested networks.

**Comment by MohseniBigBoy** [comment]
I change  `unsigned char cbits[MAX_FRAME_SIZE];` to  `unsigned char cbits[bytes_remaining];` but the result not changed. I was hoping solve problem by changing endianness, to do this, I swap odd bytes with even bytes, but it seems like a futile work.
I extract an audio file that has 8 seconds duration from [this opus pacp file ](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=sip-rtp-opus.pcap), but it is a vague voice. Is this file 8 seconds long? Where I can obtain the sound of this file, Wire-shark can not support opus decoder, however I add opus decoder to wire-shark using [this](https://github.com/volvet/h264extractor).

How to make sure that the decoding operation is done correctly?

**Comment by MohseniBigBoy** [comment]
I check extracted opus packets from RTP packets and I saw they were similar to what I saw using wireshark. You can see them [here](https://drive.google.com/file/d/1DJGHdGWPf19AW0bImNRvC4dfvE1uFzJf/view). Also you can see decoder output packets [here](https://drive.google.com/file/d/1WKo0U6adSv4MGKr7jQk4Yax5uAZQ3zKl/view) and  the obtained audio file [here](https://drive.google.com/file/d/1o_eDtT5ZRrye8f10GMJie0XX1qibOGvP/view). Note that according to modified code, first number in the saved packet files names is packet number and second number is packet length in bytes. You can see them using **_xxd_**. I check opus decoder parameters but can not extract the audio file correctly!

This is modified **_decode_** method:

```
void ELA::OpusDecoder::decode(const AudioBuffer& input, AudioBufferRef& output, char* scratch)
{
	char* in_buff_ptr = input.buffer;
	int bytes_remaining = input.details.bytes_count;
	char*  out_buff_ptr = scratch;
	uint32_t out_buff_size = 0;
	unsigned char input_of_decoder[bytes_remaining];

	memcpy(input_of_decoder, in_buff_ptr, bytes_remaining);

	static int number_of_packets = 0;
	number_of_packets++;

        std:string res_file_name = "../decoder_input_packets/" +  std::to_string(
                number_of_packets) + "_" + std::to_string(bytes_remaining);
	std::ofstream decoder_input_packets_as_text_file(res_file_name);
	decoder_input_packets_as_text_file.write(in_buff_ptr, bytes_remaining);
	decoder_input_packets_as_text_file.close();

	opus_int32 output_samples = opus_decode(decoder, input_of_decoder, 
                  bytes_remaining, (opus_int16*)out_buff_ptr, MAX_FRAME_SIZE, 0);

	res_file_name = "../decoder_output_packets/" + std::to_string(
                  number_of_packets) + "_" + std::to_string(output_samples);
	std::ofstream decoder_out_put_packets_as_text_file(res_file_name);

	if (output_samples<0)
	{
		fprintf(stderr, "\ndecoder failed: %s\n", opus_strerror(err));
		decoder_out_put_packets_as_text_file << "ERROR: " << opus_strerror(
			output_samples) << std::endl;
	}
	else
	{
		decoder_out_put_packets_as_text_file.write(out_buff_ptr, output_samples);
		out_buff_ptr += output_samples;
		out_buff_size += output_samples;
	}

	decoder_out_put_packets_as_text_file.close();

	save_output_audio_buffer(out_buff_size, scratch);
}
```
