### ISSUE TITLE
Linphone opus codec sampling rate

### ISSUE THREAD

**Issue by ehsanmqn** [xiph/opus#170]
I would like to use opus codec in linphone

But I have a few problems using it. If someone with opus codec knowledge could help me out would appreciate it. How I can force audio sampling scheme to 8000 Hz? Currently, it uses 48000 Hz only.

Thanks in advance

**Comment by rillian** [comment]
You can set a sample rate of 8000 Hz for the input/output data when you create the encoder/decoder handle. e.g.
```
int ret;
OpusEncoder *enc = opus_encoder_create(8000, 1, OPUS_APPLICATION_VOIP, &ret);
assert(ret == OPUS_OK);
[...]
OpusDecoder *dec = opus_decoder_create(8000, 1, &ret);
assert(ret == OPUS_OK);
```
But if your capture or playback devices aren't actually running at 8 kHz, it's better to run them at the native rate. You can call `opus_encoder_ctl(enc, OPUS_SET_BANDWIDTH(OPUS_NARROWBAND))` to tell the encoder not to waste bits on higher frequencies which aren't important for your application. The encoder will also do this automatically if request a sufficiently low bitrate.

Opus is meant to be flexible with respect to audio frequency: the encoder and decoder done't have to run at the same sample rate.

**Comment by ehsanmqn** [comment]
Thank you for your useful information.
