### ISSUE TITLE
Custom modes does not work with 1.3.1 anymore

### ISSUE THREAD

**Issue by hoene** [xiph/opus#172]
We are testing Soundjack with Opus 1.3.1. Soundjack is used Opus custom modes (2^n). 
Custom modes work with version 1.1.3 and 1.2.1. However, they crash with Opus 1.3.1.

**Comment by gmaxwell** [comment]
Can you bisect to figure out which change broke it?

**Comment by hoene** [comment]
Yes, will do it will the command
./opus_custom_demo 48000 1 128 1000 test.sw out.sw

**Comment by hoene** [comment]
```
# good: [ea8b26ff85fe143428cef3222b04249e80ef13d2] Fix comma that should have been a semicolon
git bisect good ea8b26ff85fe143428cef3222b04249e80ef13d2
# first bad commit: [2c0061c19bad73f49cd3f47eea440fd7799dbd90] Enable hardening by default
```

**Comment by hoene** [comment]
Indeed, if I switch off hardening, it even works with the latest master.
```
./configure --enable-custom-modes --disable-hardening
```

**Comment by jmvalin** [comment]
Thanks for bisecting. Should be simple to fix.

**Comment by hoene** [comment]
Does https://github.com/xiph/opus/pull/168 provide the fix already?

**Comment by jmvalin** [comment]
Should now be fixed (merged the PR). Please re-open if that's not the case.

**Comment by hoene** [comment]
Thanks @jmvalin
