### ISSUE TITLE
VS2015 DLL build fails to export library info functions

### ISSUE THREAD

**Issue by mquander** [xiph/opus#18]
When compiling Opus using the included VS2015 projects, the `opus_strerror` and `opus_get_version_string` functions are not exported into the resulting DLL.

This is caused because those functions are implemented in the CELT VS project, which, unlike [the Opus project](https://github.com/xiph/opus/commit/5ff11c02dabe4c857ab39f38b557782999d23224#diff-f61e8c40955aae3e36d551feb1fe2470L434), does not define the `DLL_EXPORT` preprocessor symbol (as implemented in https://github.com/xiph/opus/commit/6e9617371f7cf3f669a60d9540723a01f1128fc8).

Changing the CELT project properties to also define `DLL_EXPORT` causes the functions to be exported as expected.

(EDIT: As pointed out below, this is only a problem with 1.1.3 and has been fixed on master.)

**Comment by wiiaboo** [comment]
There are no separate VS projects for celt and silk. Are you sure you're using master branch?

**Comment by mquander** [comment]
Ah, I see. I was building from the v1.1.3 tag.

**Comment by nacho** [comment]
I am having the same problem with 1.1.3. I tried to build the alpha version but it does not seem to properly build for me. i.e the vs project points out to files that do not exists anymore. Did you have more luck here @mquander ?

**Comment by wiiaboo** [comment]
The alpha is only missing a [fix for test_opus_encode](https://github.com/xiph/opus/commit/e619ea76bfaec2b17d09d9c4283c0343d2c10e3f), but other than that there should be absolutely no references to non-existing files. Git master is also missing a fix for DebugDLL opus_demo.

**Comment by nacho** [comment]
@wiiaboo using dumpbin on the generated DLL do you see the opus_strerror method exported?

**Comment by wiiaboo** [comment]
Yes: https://i.fsbn.eu/win32-exports.txt https://i.fsbn.eu/x64-exports.txt
From opus.dll output from ReleaseDLL Win32 and x64 respectively.

**Comment by nacho** [comment]
I just tried master and I confirm it builds properly and opus_strerror is exported

**Comment by AraHaan** [comment]
Master does build properly but if you download the zip file from the official website then it will not.

**Comment by wiiaboo** [comment]
@AraHaan Github archives aren't supported by autotools build system and soon won't be supported by the windows build system: #13

**Comment by AraHaan** [comment]
you do know the download as zip button on the base of the repo if you was to copy that link address it is supported then the end users would not know you did not upload any zip files.
like the one for master on this repo is: https://github.com/xiph/opus/archive/master.zip besides no matter how the website is made it is supported to link the zip file from another location. That is what I meant by having the official page allow the user to download the master zip file from this github repo without actually needing to go to this repo. This then eliminates needing to upload a zip file or whatever archive format it does support directly to the official site.

**Comment by wiiaboo** [comment]
It's supported by Github, obviously, but not by the developers of Opus. The zip archive of a git repository is not the same thing as the git repository or a tarball of a release.

**Comment by nacho** [comment]
I just tested 1.1.4 and the problem persists.... :(

**Comment by wiiaboo** [comment]
1.1.4 doesn't include any changes to the VS tree.

**Comment by jmvalin** [comment]
Not going to fix for 1.1.x, but based on what I see here, it'll work for 1.2, which should be out in the not too far future, so it should be good. Please reopen if this is incorrect.
