### ISSUE TITLE
Stereo audio becoming mono after encoding and decoding at 8000 Hz

### ISSUE THREAD

**Issue by theeasiestway** [xiph/opus#181]
Hello! I use Opus on android and encode my pcm stereo audio (16 bit 8 kHz) and then I decode it and play it on the same device and the result sound is mono, it sounds like there is no the separation between left and right channel that was before encoding and decoding.
I init my encoder like this:
```
int size = opus_encoder_get_size(2);
OpusEncoder* encoder = (OpusEncoder*) malloc((size_t) size);
opus_encoder_init(encoder, 8000, 2, 2049);
```
And decoder like this:
```
int size = opus_decoder_get_size(2);
OpusDecoder* decoder = (OpusDecoder*) malloc((size_t) size);
opus_decoder_init(decoder, 8000, 2);
```
And [here](https://github.com/xiph/opus/files/4681363/Android.txt) my Android.mk script that I used to compile the library.
The versions that I used for compile:
libopus 1.3.1 and libopusenc 0.2.1

What am I doing wrong?

**UPD 27.05.2020**
Stereo audio becomes mono if I use sample rate 8000 Hz but if I use 48000 Hz everything works fine is it a correct behaviour?

**Comment by silverbacknet** [comment]
Auto-downmixing is based on bitrate, below 17kbps it'll hard downmix to mono. (Or 19kbps for speech.) You can use OPUS_SET_FORCE_CHANNELS_REQUEST to force it to stereo anyway, but the stereo image will likely be much narrower than expected at such low bitrates.

**Comment by theeasiestway** [comment]
Ok thanks
