### ISSUE TITLE
Is this method thread safe? 

### ISSUE THREAD

**Issue by dingqunfei** [xiph/opus#185]
Is this method thread safe?
I want to use multithreading to call the API, but i see some non-const static variables

**Comment by rillian** [comment]
You don't say which method.

Except when built with the non-threadsafe pseudostack option for embedded environments, opus is re-entrant. That is, it's safe to call methods from what ever thread you like. But it's *not* safe to call multiple methods on the same context simultaneously.

Clients are expected to perform their own locking around access to an encoder or decoder context state objects if they need to perform access from multiple threads. Library functions which don't take a state object are safe to call without locking.

Does that answer your question?

**Comment by dingqunfei** [comment]
> You don't say which method.
> 
> Except when built with the non-threadsafe pseudostack option for embedded environments, opus is re-entrant. That is, it's safe to call methods from what ever thread you like. But it's _not_ safe to call multiple methods on the same context simultaneously.
> 
> Clients are expected to perform their own locking around access to an encoder or decoder context state objects if they need to perform access from multiple threads. Library functions which don't take a state object are safe to call without locking.
> 
> Does that answer your question?

I want to use multithreading to call the decoding API, they are in a thread queue waiting for. 
Any thread may receive one wav to decoding,  and every thread has its own decoder state for decoding in a loop. Does every thread need locking?

**Comment by rillian** [comment]
If every thread has its own `OpusDecoder` state, you do not need locking.

**Comment by dingqunfei** [comment]
> If every thread has its own `OpusDecoder` state, you do not need locking.

OK, thanks
