### ISSUE TITLE
opus.def LIBRARY set to libogg

### ISSUE THREAD

**Issue by mipac** [xiph/opus#192]
when compile with cmak/mingw64 with msys2 shell
ogg.def is used
LIBRARY must be set to libogg, and then the executables will looking for libogg.dll, and not ogg.dll like now

flac and opus don't use a .def, and it works fine
is it necessary?

**Comment by xnorpx** [comment]
Sorry, I am not so familiar with msys2 and mingw64, can you provide step by step instructions how you compile and the exact issue you are seeing.

**Comment by mipac** [comment]
sorry ... the issue is for ogg !!!

**Comment by xnorpx** [comment]
no problem

**Comment by mipac** [comment]
i post the issue to the ogg project ;)
