### ISSUE TITLE
The test vectors link in the README is wrong.

### ISSUE THREAD

**Issue by lu-zero** [xiph/opus#193]
`https://opus-codec.org/docs/opus_testvectors-rfc8251.tar.gz` gives 404

**Comment by xnorpx** [comment]
You can find them here as well: https://archive.mozilla.org/pub/opus/opus_testvectors-rfc8251.tar.gz 

but link should be fixed @rillian @mark4o ?

**Comment by lu-zero** [comment]
I have a local copy already, but would be nice to update the README or fix the link :)

**Comment by rillian** [comment]
I've restored the redirects, so this should work now. Thanks for the report!
