### ISSUE TITLE
compile error on visual studo 2015.

### ISSUE THREAD

**Issue by dttlgotv** [xiph/opus#199]
I got the newest cocdes and open .sln on visaul studio 2015 to compile it. But the 144 error, it looks like below:

![图片](https://user-images.githubusercontent.com/5996999/93843477-88fc8580-fccc-11ea-84ea-ed7527bd822e.png)

VS do not support variable size array, but it is strange that I can not find any solution to fix it. But It seems you can do it.

**Comment by mark4o** [comment]
Opus can use either alloca() or VLAs.  On Windows, the win32/config.h file defines USE_ALLOCA, so the ALLOC macro will use alloca() and not VLAs.  This is building successfully on Microsoft Visual Studio in Appveyor: https://ci.appveyor.com/project/rillian/opus/builds/34795037/job/u06o794ym4lks8o6

**Comment by dttlgotv** [comment]
undefine it？



发自我的iPhone


------------------ Original ------------------

**Comment by dttlgotv** [comment]
> Appveyor

I must modify config.h like below, then everything run well.

/* Make use of alloca */
 #define  USE_ALLOCA  1

/* Use C99 variable-size arrays */
//#define VAR_ARRAYS 1

**Comment by xnorpx** [comment]
I don't see VAR_ARRAYS defined in this config.h ?

https://github.com/xiph/opus/blob/master/win32/config.h

**Comment by xnorpx** [comment]
You must have generated a config.h with autotools and then tried to used that when building the vs solution?

**Comment by dttlgotv** [comment]
> 
> 
> You must have generated a config.h with autotools and then tried to used that when building the vs solution?

Using cmake to produce vs solution, then everything is well.
