### ISSUE TITLE
make lib size smaller, Is it possible

### ISSUE THREAD

**Issue by xsjqqq123** [xiph/opus#20]
hello, boys. We have decide to use opus in our product. but the size of lib complied to more than 200KB is also too larger to use. is that any options to cut off the size?  we only need speech , music is not necessary, can these part be cut?

**Comment by AraHaan** [comment]
compress the library with something like UPX or Petite?
UPX can be found on sourceforge.
Petite on otherhand can only be found here: https://www.un4seen.com/petite

**Comment by jmvalin** [comment]
You can compile with SMALL_FOOTPRINT defined to save a few kB at the expense of more CPU requirement. For fixed-point builds, you can save a little by defining DISABLE_FLOAT_API. You may also be able to save by manually removing some features you don't need (e.g. parts of the encoder). Other than that, libopus is already as small as we can make it.
