### ISSUE TITLE
Any introduction to compile ios and android using cmake?

### ISSUE THREAD

**Issue by dttlgotv** [xiph/opus#200]
Currently opus has added cmake build system. It is very good to compile opus library on windows and macosx. 

But it is no introduction to compile opus library to be used on ios and android, maybe I missed something. Please give me a hint.

Thanks a lot.

**Comment by xnorpx** [comment]
https://developer.android.com/ndk/guides/cmake
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos
https://github.com/xnorpx/opus/blob/master/.github/workflows/build.yml

Should get you started.

**Comment by dttlgotv** [comment]
> 
> 
> https://developer.android.com/ndk/guides/cmake
> https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos
> https://github.com/xnorpx/opus/blob/master/.github/workflows/build.yml
> 
> Should get you started.

Thanks
