### ISSUE TITLE
Decoding opus packets coming from multiple sources outputs undefined content.

### ISSUE THREAD

**Issue by HeyShafty** [xiph/opus#202]
I am currently developping a simple audio packet sender using VOIP protocol. I am currently stuck on an issue that outputs glitchy audio when recieving audio packets from **MORE THAT ONE** source.

**Scenario example:**
User A recieves audio packet from user B => **audio is clear**, decoding gives expected result.
User A recieves audio packet from user B, and user C starts sending audio packets => audio becomes glitchy, decoding gives unexpected result.
User C stops sending audio packets => **audio is clear**, decoding gives expected result.

**What do I mean by "expected result":**
Let's say I am sending a muted microphone input (sample array is filled with '0's), non-encoded input audio corresponds to decoded audio output after going through encoding, network and decoding:
![image](https://user-images.githubusercontent.com/44643483/94805766-2fdbd280-03ed-11eb-8b5f-827dfa6dddbb.png)

Each and every packet always decode into this very same result.

**What do I mean by "unexpected result":**
Exact same muted microphone input, but suddently output starts being "random".
![image](https://user-images.githubusercontent.com/44643483/94806054-a7116680-03ed-11eb-80dd-5477d45f2e71.png)
![image](https://user-images.githubusercontent.com/44643483/94806500-53ebe380-03ee-11eb-9e9d-dd956fc9ecda.png)

The only difference between last paragraph, is that I am decoding packets coming from an additional source.

I am suspecting that decoding audio from different threads might be the cause of this issue, but I can't either be sure, or find a fix for that.

I'm not sure if everything is clear, but I can provide source code if that help.

Sample rate: 48000
Channel count: 2

**Comment by silverbacknet** [comment]
Essentially, all you're showing here is how efficient Opus is at recovering from corruption, because by mixing unrelated streams, you're corrupting the bitstream.

You need to have a separate context for each stream, and mix them after decoding, not while decoding.

**Comment by HeyShafty** [comment]
I am not trying to mix the packages together during the decoding process, but I _may_ be decoding packages on the same context.
