### ISSUE TITLE
can you decode multiple files at once?

### ISSUE THREAD

**Issue by aaaaaaaaahhhhh** [xiph/opus#217]
apologies if this is a commonly asked issue. is there any way to decode multiple files at once using opusdec.exe? if not, is there some other program that can? im not particularly savvy with this stuff

**Comment by silverbacknet** [comment]
With opusdec/opusenc, you can only run multiple instances in parallel; this is how Foobar2000's transcoder works, for instance. (Note that the command line is actually part of the https://github.com/xiph/opus-tools project, while this is the code internals.)

By using the library directly, you can create a threadpool that can encode as many streams at once internally as you want, but that requires significant programming skill. That's how high end platforms like RadioMast and YouTube work.

**Comment by aaaaaaaaahhhhh** [comment]
yeah, i dont think ill be doing that on account of me not knowing how to code. thanks i guess.

maybe theres a script somewhere...
