### ISSUE TITLE
segmentation fault on windows for all tests

### ISSUE THREAD

**Issue by mrrostam** [xiph/opus#231]
Hey folks,

I am trying to build the opus library on Windows (mingw32) using cmake:

```console
mkdir build
cd build
cmake .. -G "MinGW Makefiles" -DBUILD_TESTING=1
mingw32-make.exe
./testing_opus_api.exe
```

but then I get `segmentation fault`.

Any help would be appreciated.

**Comment by mrrostam** [comment]
@xnorpx i guess you might know the answer

**Comment by rillian** [comment]
It's hard to know what went wrong from what you've posted. Can you try running `testng_opus_api.exe` under a debugger to get a stack trace from the crash?

**Comment by xnorpx** [comment]
@mrrostam can you share what mingw32 (link to binary) and how you set it up?

**Comment by xnorpx** [comment]
Could not repro with my install, so please provide step by step how to repro, or stack trace as @rillian suggested.

mingw is a little uncharted territory for me so might do things wrong

downloaded from https://sourceforge.net/projects/mingw-w64/
added C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/ to path
cmd
cd C:\git\opus
mkdir build
cd build

C:\git\opus\build>cmake .. -G "MinGW Makefiles" -DBUILD_TESTING=1
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.27.0.windows.1")
-- Opus package version from git repo: 1.3.1-97-g6b6035ae
-- Opus project version: 1.3.1
-- The C compiler identification is GNU 8.1.0
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc.exe
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc.exe - works
....

mingw32-make.exe
[ 94%] Built target opus
[ 95%] Built target test_opus_api
[ 96%] Built target test_opus_decode
[ 98%] Built target test_opus_padding
[100%] Built target test_opus_encode

C:\git\opus\build>ctest
Test project C:/git/opus/build
    Start 1: test_opus_decode
1/4 Test #1: test_opus_decode .................   Passed   16.88 sec
    Start 2: test_opus_padding
2/4 Test #2: test_opus_padding ................   Passed    0.04 sec
    Start 3: test_opus_api
3/4 Test #3: test_opus_api ....................   Passed    4.07 sec
    Start 4: test_opus_encode
4/4 Test #4: test_opus_encode .................   Passed   47.26 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =  68.26 sec

**Comment by mrrostam** [comment]
@xnorpx Thank you for your prompt reply, regarding mingw, I got mine from [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download). Then selected x86_64 for `Architecture` and posix for `Threads`.

**Comment by mrrostam** [comment]
@xnorpx @rillian Thank you guys for your prompt reply; 

Regarding mingw, I got mine from the same location as you mentioned. I am not sure if it makes any difference, but i selected x86_64 instead of the default i686 for the architecture. Even for the `ctest`, I am getting all `failed with result Access violation`.

@rillian -> I'll do the stack trace to get the root of this issue shortly; meanwhile I noticed if I turn both `STACK_PROTECTOR_SUPPORTED` and `FORTIFY_SOURCE_SUPPORTED` options off, that would solve the problem

**Comment by xnorpx** [comment]
@mrrostam can you check if i686 works for you, I can test x86_64

**Comment by xnorpx** [comment]
yeah it's a repro on x86_64 need to see how to debug this thing.

**Comment by xnorpx** [comment]
https://medium.com/@pamirghimire/debugging-with-gdb-on-windows-using-visual-studio-code-81ba70b562f3

**Comment by mrrostam** [comment]
@xnorpx correct, tried i686 and got no errors

**Comment by xnorpx** [comment]
Looks like there is an issue with the stack protection in that version of GCC that is included in MINGW that can be downloaded: https://github.com/msys2/MINGW-packages/issues/4266

So what you can do is either.

Stick with the version you are using but disable the stack protector.
cmake .. -G "MinGW Makefiles" .. -DOPUS_BUILD_TESTING=ON -DOPUS_STACK_PROTECTOR=OFF
mingw32-make.exe -j 32
ctest -j 4

Download a newer version of mingw64 from https://winlibs.com/
I downloaded https://github.com/brechtsanders/winlibs_mingw/releases/download/10.3.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-10.3.0-mingw-w64-9.0.0-r2.zip

I unzipped it in a folder added to path and removed the older mingw path from path.

where gcc
C:\git\opus\build>where gcc
C:\Program Files\mingw-w64\gcc10\mingw64\bin\gcc.exe
C:\git\opus\build>"C:\Program Files\mingw-w64\gcc10\mingw64\bin\gcc.exe" --version
gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Now I could build with.
cmake .. -G "MinGW Makefiles" .. -DOPUS_BUILD_TESTING=ON
-- The C compiler identification is GNU 10.3.0
-- Check for working C compiler: C:/Program Files/mingw-w64/gcc10/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/Program Files/mingw-w64/gcc10/mingw64/bin/gcc.exe - works
mingw32-make.exe -j 32
ctest -j 4

C:\git\opus\build>ctest -j 4
Test project C:/git/opus/build
    Start 1: test_opus_decode
    Start 2: test_opus_padding
    Start 3: test_opus_api
    Start 4: test_opus_encode
1/4 Test #2: test_opus_padding ................   Passed    0.07 sec
2/4 Test #3: test_opus_api ....................   Passed    1.94 sec
3/4 Test #1: test_opus_decode .................   Passed   10.69 sec
4/4 Test #4: test_opus_encode .................   Passed   20.11 sec

Hope this helps!

**Comment by mrrostam** [comment]
@xnorpx you're right! I could build and test the library without any issue using the suggested version of mingw.

Thanks again for the help :)
