### ISSUE TITLE
Latest release v1.3.1 is two years old?

### ISSUE THREAD

**Issue by tt37** [xiph/opus#235]
According to https://github.com/xiph/opus/releases, latest release is `v1.3.1` from two years ago.

Additionally, the latest release shown on the main GitHub page at https://github.com/xiph/opus shows the even older tag `opus-1.1.2` from 2016 as latest release.

This leads to the impression that no significant changes have been made in the last two years or it was forgotten to create a newer tag/release.

Would it be possible to create a new release?
If not, what are the issues blocking a release?

Thanks for a response

**Comment by vtorri** [comment]
i agree. There are several fixes and also build system improvements, which could justify a new release

**Comment by jlw4049** [comment]
Yeah, I was wondering this same thing

**Comment by LuisB79** [comment]
you mean 3 years? :c

**Comment by unityfeth** [comment]
It would be great to get some of the fixes in master into a stable release, particularly the change to enable OPUS_PRESUME_NEON for iOS platforms (7628d844).

I'm not familiar with the release process. Who is familiar with it and could make a v1.3.2(?) release?

**Comment by jlw4049** [comment]
Yeah I really dont understand why there hasn't been an updated release posted tbh

**Comment by zdravkin** [comment]
@jmvalin can you please help us here?
The rule of thumb is that we can use only a released version, and the 1.3.1 has been released a long time ago.
Is it possible to create a new tag if the master branch is stable?
Thank you

**Comment by LuisB79** [comment]
Opus 1.4 when

**Comment by marcan** [comment]
Wow, just realized it's been this long without a release. I remember fixing 4d406367 two years ago, it's unfortunately it still isn't released...

**Comment by Bits360** [comment]
2023 and still no 1.4. Is something big in the works? Or did something bad happen?

**Comment by vtorri** [comment]
i'm wondering if the xiph project is  still alive or not. See the [status here](https://github.com/orgs/xiph/repositories?q=&type=all&language=&sort=). Only a couple of projects  have _significant_ commits recently. ogg, libvorbis, speex  and libtheora seem dead

**Comment by silverbacknet** [comment]
Speex, theora, and vorbis are all ancient legacy tech that isn't going to see any investment beyond security updates, or a corporate sponsorship by some entity invested in their improvement. Ogg is a very simple thing that Just Works™ and won't ever need much in the way of updates.

Opus is still active, as are a number of other Xiph projects, like rav1e; the big problem right now seems to be the lack of a release manager. jmv can only wear so many hats for so many projects at once. I would assume that a release manager has to handle a significant amount of compatibility testing for such a huge project, an perhaps liaison with major sponsors. But I also assume anyone willing to step up and do it would be welcomed.

**Comment by ThreeDeeJay** [comment]
The [binaries compiled in Appveyor are already expired](https://ci.appveyor.com/project/rillian/opus/builds/45969426/job/ibpylqrj85x7ykme/artifacts) so the can't be downloaded anymore.
I forked and [rebuilt it here](https://ci.appveyor.com/project/3DJ/opus/builds/46476331) so perhaps one of the maintainers could also add binaries to GitHub (pre)releases so they can be found more easily from a permanent (non-expiring) location.
I'd submit a PR with a Github actions workflow that does it automatically on every push, but apparently Opus is still using VS2015 which I've never had luck building with (at the moment there are only 2019 and 2022 runner images).

**Comment by tt37** [comment]
Thanks to everyone involved in releasing version [1.4](https://github.com/xiph/opus/releases/tag/v1.4)
