### ISSUE TITLE
ctest can not run well

### ISSUE THREAD

**Issue by dttlgotv** [xiph/opus#245]
I got the neweset opus code and want to run in window.  Building is well, but ctest can not run well.

1. cmake .. -A Win32 -DOPUS_BUILD_TESTING=ON
fatal: No names found, cannot describe anything.
CMake Warning at cmake/OpusPackageVersion.cmake:61 (message):
  Could not get package version.
Call Stack (most recent call first):
  CMakeLists.txt:5 (get_package_version)

-- Opus project version: 0
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- Performing Test VLA_SUPPORTED -- failed to compile
-- Check SIMD support by compiler
-- The following features have been enabled:

 * OPUS_BUILD_TESTING, build tests.
 * OPUS_ENABLE_FLOAT_API, compile with the floating point API (for machines with float library).
 * OPUS_HARDENING, run-time checks that are cheap and safe for use in production.
 * OPUS_INSTALL_PKG_CONFIG_MODULE, install pkg-config module.
 * OPUS_INSTALL_CMAKE_CONFIG_MODULE, install CMake package config module.
 * OPUS_USE_ALLOCA, use alloca for stack arrays (on non-C99 compilers).
 * OPUS_STACK_PROTECTOR, use stack protection.
 * OPUS_X86_MAY_HAVE_SSE, does runtime check for SSE1 support.
 * OPUS_X86_MAY_HAVE_SSE2, does runtime check for SSE2 support.
 * OPUS_X86_MAY_HAVE_SSE4_1, does runtime check for SSE4.1 support.
 * OPUS_X86_MAY_HAVE_AVX, does runtime check for AVX support.

-- The following OPTIONAL packages have been found:

 * Git

-- The following features have been disabled:

 * OPUS_BUILD_SHARED_LIBRARY, build shared library.
 * OPUS_CUSTOM_MODES, enable non-Opus modes, e.g. 44.1 kHz & 2^n frames.
 * OPUS_BUILD_PROGRAMS, build programs.
 * OPUS_DISABLE_INTRINSICS, disable all intrinsics optimizations.
 * OPUS_FIXED_POINT, compile as fixed-point (for machines without a fast enough FPU).
 * OPUS_FLOAT_APPROX, enable floating point approximations (Ensure your platform supports IEEE 754 before enabling).
 * OPUS_ASSERTIONS, additional software error checking.
 * OPUS_FUZZING, causes the encoder to make random decisions (do not use in production).
 * OPUS_CHECK_ASM, enable bit-exactness checks between optimized and c implementations.
 * OPUS_FIXED_POINT_DEBUG, debug fixed-point implementation.
 * OPUS_VAR_ARRAYS, use variable length arrays for stack arrays.
 * OPUS_NONTHREADSAFE_PSEUDOSTACK, use a non threadsafe pseudostack when neither variable length arrays or alloca is supported.
 * OPUS_FAST_MATH, enable fast math (unsupported and discouraged use, as code is not well tested with this build option).
 * OPUS_X86_PRESUME_SSE, assume target CPU has SSE1 support (override runtime check).
 * OPUS_X86_PRESUME_SSE2, assume target CPU has SSE2 support (override runtime check).
 * OPUS_X86_PRESUME_SSE4_1, assume target CPU has SSE4.1 support (override runtime check).
 * OPUS_X86_PRESUME_AVX, assume target CPU has AVX support (override runtime check).

2. cmake --build .
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt
  opus.vcxproj -> C:\AiAudio\eeo_opus\build\Debug\opus.lib
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt
  test_opus_api.vcxproj -> C:\AiAudio\eeo_opus\build\Debug\test_opus_api.exe
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt
  test_opus_decode.vcxproj -> C:\AiAudio\eeo_opus\build\Debug\test_opus_decode.exe
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt
  test_opus_encode.vcxproj -> C:\AiAudio\eeo_opus\build\Debug\test_opus_encode.exe
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt
  test_opus_padding.vcxproj -> C:\AiAudio\eeo_opus\build\Debug\test_opus_padding.exe
  Building Custom Rule C:/AiAudio/eeo_opus/CMakeLists.txt

3. ctest
Test project C:/AiAudio/eeo_opus/build
    Start 1: test_opus_decode
Test not available without configuration.  (Missing "-C <config>"?)
1/4 Test #1: test_opus_decode .................***Not Run   0.00 sec
    Start 2: test_opus_padding
Test not available without configuration.  (Missing "-C <config>"?)
2/4 Test #2: test_opus_padding ................***Not Run   0.00 sec
    Start 3: test_opus_api
Test not available without configuration.  (Missing "-C <config>"?)
3/4 Test #3: test_opus_api ....................***Not Run   0.00 sec
    Start 4: test_opus_encode
Test not available without configuration.  (Missing "-C <config>"?)
4/4 Test #4: test_opus_encode .................***Not Run   0.00 sec

0% tests passed, 4 tests failed out of 4

Total Test time (real) =   0.02 sec

The following tests FAILED:
          1 - test_opus_decode (Not Run)
          2 - test_opus_padding (Not Run)
          3 - test_opus_api (Not Run)
          4 - test_opus_encode (Not Run)
Errors while running CTest
Output from these tests are in: C:/AiAudio/eeo_opus/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

LastTest.log is 
Start testing: Feb 21 16:04 ?D1ú±ê×?ê±??
----------------------------------------------------------
Test not available without configuration.  (Missing "-C <config>"?)
1/4 Testing: test_opus_decode
1/4 Test: test_opus_decode
Command: "NOT_AVAILABLE"
Directory: C:/AiAudio/eeo_opus/build
"test_opus_decode" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"test_opus_decode" end time: Feb 21 16:04 ?D1ú±ê×?ê±??
"test_opus_decode" time elapsed: 00:00:00
----------------------------------------------------------

Test not available without configuration.  (Missing "-C <config>"?)
2/4 Testing: test_opus_padding
2/4 Test: test_opus_padding
Command: "NOT_AVAILABLE"
Directory: C:/AiAudio/eeo_opus/build
"test_opus_padding" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"test_opus_padding" end time: Feb 21 16:04 ?D1ú±ê×?ê±??
"test_opus_padding" time elapsed: 00:00:00
----------------------------------------------------------

Test not available without configuration.  (Missing "-C <config>"?)
3/4 Testing: test_opus_api
3/4 Test: test_opus_api
Command: "NOT_AVAILABLE"
Directory: C:/AiAudio/eeo_opus/build
"test_opus_api" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"test_opus_api" end time: Feb 21 16:04 ?D1ú±ê×?ê±??
"test_opus_api" time elapsed: 00:00:00
----------------------------------------------------------

Test not available without configuration.  (Missing "-C <config>"?)
4/4 Testing: test_opus_encode
4/4 Test: test_opus_encode
Command: "NOT_AVAILABLE"
Directory: C:/AiAudio/eeo_opus/build
"test_opus_encode" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"test_opus_encode" end time: Feb 21 16:04 ?D1ú±ê×?ê±??
"test_opus_encode" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Feb 21 16:04 ?D1ú±ê×?ê±??

**Comment by xnorpx** [comment]
For multiconfig builds you need to specify which config you built.

Example:

cd opus
mkdir build
cd build
cmake .. -DOPUS_BUILD_TESTING=ON
cmake --build . -j 8 --config Debug
ctest -C Debug -j 4

Relevant issue, https://gitlab.kitware.com/cmake/cmake/-/issues/20283

**Comment by dttlgotv** [comment]
> For multiconfig builds you need to specify which config you built.
> 
> Example:
> 
> cd opus mkdir build cd build cmake .. -DOPUS_BUILD_TESTING=ON cmake --build . -j 8 --config Debug ctest -C Debug -j 4
> 
> Relevant issue, https://gitlab.kitware.com/cmake/cmake/-/issues/20283

Got! Thanks a lot.
