### ISSUE TITLE
Encoding result differs on x64 Intel/AMD platforms

### ISSUE THREAD

**Issue by TetraSomia** [xiph/opus#259]
Hi!
First, thank you for this awesome codec!

We have been using it a lot and noticed some small variations between encodings on AMD and Intel x86_64 platforms.
I understand that getting a completely deterministic result is not one of your priorities, but I wondered if it would be possible to add a compile option that would allow it.
It may be interesting for people like us that use checksum of the encoded Opus to track updates.

I pinpointed the two instructions that cause such variations, it's SSE's RCPPS and RSQRTPS, both located in `op_pvq_search_sse2()`.
My "fix" was to use their non-approximative counterparts, thus replacing:
https://github.com/xiph/opus/blob/997fdf54e781ae1c04dee42018f35388a04fe483/celt/x86/vq_sse2.c#L108
by: `rcp4 = _mm_mul_ps(_mm_set_ps1((float)(K+.8)), _mm_div_ps(_mm_set_ps1(1.0f), sums));`, and:
https://github.com/xiph/opus/blob/997fdf54e781ae1c04dee42018f35388a04fe483/celt/x86/vq_sse2.c#L173
by: `y4 = _mm_div_ps(_mm_set_ps1(1.0f), _mm_sqrt_ps(y4));`

Only replacing RSQRTPS seemed to do the trick, but replacing both of them allows to get the same result as with `op_pvq_search_c()` (at least with our MSVC).
Unfortunately I did not benchmark those changes.

What do you think about it? Does a macro such as OPUS_X86_DISABLE_SSE_APPROX to switch off those instructions would be a good approach?

Thanks!

**Comment by silverbacknet** [comment]
I'm not sure the difference would even rise above measurement noise on any platform that can support x64, and I doubt it would ever be meaningful, it's so quick already. Most likely the "approximate" part of those instructions was just not noticed, since they're identical in x86 mode. (The RCPPS is outside the loop, so swapping it wouldn't even exist on a profile anyway.)

**Comment by jmvalin** [comment]
If you want completely deterministic, you probably better stick to fixed point -- and even then I'm not 100% sure. With floating-point every compiler version, compile flag, build option, ... will change the result. Even if you consider a particular binary, there are other CPU-dependent bits of code that will change the results. For example, if the C code computes (a+b)+c and SSE computes a+(b+c), then the results may be different. Similarly, I believe the same a+b*c can give a different result depending on whether it's computed using mul and add, or using a fused multiply-add.

**Comment by TetraSomia** [comment]
Thank you for the quick replies!

Indeed using fixed point might be the safest way to go, but I was worried about the performance and quality impact as suggested in the README.

However, our use case really focus on a single DLL, which is compiled once, and runs on both platforms. So from what I understand, the resulting Opus may only vary based on runtime CPU feature detection (using CPUID), and from the "approximate" instructions that I mentioned above (I found those [here](https://stackoverflow.com/questions/13102167/do-fp-operations-give-exactly-the-same-result-on-various-x86-cpus), but the list might not be exhaustive).

On our CPUs, the SSE/AVX/FMA/... feature set seems equivalent on AMD and Intel, so we are only left with the approx-instructions causing trouble.

So yeah... Our use case might be a bit specific, and not worth the macro 😄 

Anyway, thanks for the insights!
