### ISSUE TITLE
"Patents essential to the opus codec"

### ISSUE THREAD

**Issue by LuisB79** [xiph/opus#264]
An UK-based IP and technology licensing company Vectis IP announced a call for patents essential to the Opus codec. Initial participants in Vectis IP’s prospective pool include Fraunhofer and Dolby. Did Vectis IP ask for consent of Jean-Marc Valin,  Koen Vos,  Timothy B. Terriberry, and the entire Xiph.Org team?

**Comment by fabiorug** [comment]
this is a repo, github shouldn't be used to discuss legal issues or to talk about usac.

**Comment by 32-bit-link** [comment]
Got to agree with fab here, a github issue really isn't the place to discuss legal issues. 
I'm sure the team over at Xiph.Org is aware and is taking action against this.

**Comment by LuisB79** [comment]
> this is a repo, github shouldn't be used to discuss legal issues or to talk about usac.



> Got to agree with fab here, a github issue really isn't the place to discuss legal issues. I'm sure the team over at Xiph.Org is aware and is taking action against this.

This is not topic for discussion, this is merely an awareness post.
