### ISSUE TITLE
Array out of bounds in silk stereo

### ISSUE THREAD

**Issue by heshpdx** [xiph/opus#271]
We are indexing into arrays with negative indices. When `n=0`, evaluation starts with `x1[-2]`. Is that ok? What is the intent here?

https://github.com/xiph/opus/blob/master/silk/stereo_LR_to_MS.c#L64
```
    ALLOC( side, frame_length + 2, opus_int16 );
    /* Convert to basic mid/side signals */
    for( n = 0; n < frame_length + 2; n++ ) {
        sum  = x1[ n - 2 ] + (opus_int32)x2[ n - 2 ];
        diff = x1[ n - 2 ] - (opus_int32)x2[ n - 2 ];
        mid[  n ] = (opus_int16)silk_RSHIFT_ROUND( sum, 1 );
        side[ n ] = (opus_int16)silk_SAT16( silk_RSHIFT_ROUND( diff, 1 ) );
    }
```

**Comment by rillian** [comment]
If you look at the [sole call site](https://github.com/xiph/opus/blob/v1.3.1/silk/enc_API.c#L421) it passes a pointer to the second element of the two arrays so I think it is in fact ok.

Definitely not a safety-oriented style. I assume it make some optimization easier.
Did you find input which triggers out out-of-bounds access at runtime, or is this just a local code lint?

**Comment by heshpdx** [comment]
Ok cool. It was just a local code lint. Thanks!
