### ISSUE TITLE
Missing CMake option to disable building API documentation

### ISSUE THREAD

**Issue by brad0** [xiph/opus#274]
There are options for disabling the API documentation build with autoconf and Meson but I don't see such option with CMake.

**Comment by xnorpx** [comment]
There is no API docs :) in the CMake build

https://gitlab.xiph.org/xiph/opus/-/issues/2333

**Comment by brad0** [comment]
> There is no API docs :) in the CMake build
> 
> https://gitlab.xiph.org/xiph/opus/-/issues/2333

My bad. I very quickly took a look at the CMake bits and assumed there was build infrastructure there but just missing an option to disable said support. I've seen stuff like this or even what you ultimately said with projects with multiple build infrastructure.
