### ISSUE TITLE
opus_custom_demo problem with 32 Khz

### ISSUE THREAD

**Issue by rasky** [xiph/opus#298]
I am testing opus_custom_demo with a 32 Khz file, frame size 640 bytes (20 ms). 
I configured opus 1.4 with `./configure --enable-custom-modes` to build the custom mode demo.

```
    General configuration:

      Floating point support: ........ yes
      Fast float approximations: ..... no
      Fixed point debugging: ......... no
      Inline Assembly Optimizations: . No inline ASM for your platform, please send patches
      External Assembly Optimizations:
      Intrinsics Optimizations: ...... ARM (NEON) (NEON Aarch64)
      Run-time CPU detection: ........ no
      Custom modes: .................. yes
      Assertion checking: ............ no
      Hardening: ..................... yes
      Fuzzing: ....................... no
      Check ASM: ..................... no

      API documentation: ............. yes
      Extra programs: ................ yes
 ```

I tried with the `carcombat_sketch32.raw` file attached to this issue (format is 16-bit, 2 channels, 32 Khz).
[carcombat_sketch32.raw.zip](https://github.com/xiph/opus/files/12423730/carcombat_sketch32.raw.zip)

I used this command line:

```
./opus_custom_demo 32000 2 640 160 carcombat_sketch32.raw carcombat_sketch32_out.raw
```

the conversion process went through, but the output file has a distinct "thumping" noise on the right channel. I've attached the decoded file in wav format to simplify listening.
[carcombat_sketch32_out.wav.zip](https://github.com/xiph/opus/files/12423754/carcombat_sketch32_out.wav.zip)

It sounds like some encoding or decoding bug to me. Did I make any mistake during the build process? Is the custom modes support stable and tested as working, even though it is not built by default?

**Comment by rasky** [comment]
@mikkeldamsgaard I've seen your issue about using CELT in custom mode on embedded system; I'm trying something similar but I'm hitting a problem as described in this issue. I'm just testing the custom mode demo as-is, without modifications but it seems not to work correctly for me at least. Did you experiment something similar? What custom modes are you using?

**Comment by jmvalin** [comment]
Can you give this patch a try and see if it fixes the problem:
https://jmvalin.ca/misc_stuff/opus_custom_fix.patch

**Comment by rasky** [comment]
@jmvalin thanks, that seems to fix the bug!

**Comment by rasky** [comment]
Fixed by https://github.com/xiph/opus/commit/101a71e03bbf860aaafb7090a0e440675cb27660
