### ISSUE TITLE
Conditional include for dred_coding.h 

### ISSUE THREAD

**Issue by Igor-Palaguta** [xiph/opus#313]
`#include "silk/dred_coding.h"` should be included conditionally in opus_encoder.c

```C
#ifdef ENABLE_DRED
#include "silk/dred_coding.h"
#endif
```

**Comment by jmvalin** [comment]
Fixed. Just curious, was that midding #ifdef breaking anything? If so, how?

**Comment by Igor-Palaguta** [comment]
Thanks, making opus wrapper for iOS (Cocoapod), and compiling it without DRED_SOURCES. And after I excluded them, it stopped building.

Btw. Please can you note will opus still work fine without sources: DEEP_PLC_SOURCES, DRED_SOURCES, OSCE_SOURCES, LOSSGEN_SOURCES. Probably even without whole dnn folder. Unfortunately it is not easy to find in docs what sources are required for library without tests, demo and other

**Comment by jmvalin** [comment]
All the stuff in dnn/ is optional and Opus is still supposed to be able to build without it like before. Please report any instance where that isn't the case.

**Comment by Igor-Palaguta** [comment]
Thank you for fast feedbacks! Are celt and silk folders sources are all required?

**Comment by jmvalin** [comment]
Not sure what your questions means. Can you elaborate?

**Comment by jmvalin** [comment]
Some of the source files from silk aren't needed if you disable the dnn/ stuff. Also, some more files may or may not be needed depending on the exact switches you use. Plus the contents of src/ is going to be needed. But I'm not sure why you care about the sources files here. Just provide them all and the build system will handle what it needs to compile.

**Comment by Igor-Palaguta** [comment]
Should celt.h include `#include "lpcnet.h"`
You mentioned that dnn sources are optional, and this `lpcnet.h` belongs to dnn

**Comment by jmvalin** [comment]
Well, that also should have been behind an #ifdef

**Comment by Igor-Palaguta** [comment]
Thanks a lot for you help!
