### ISSUE TITLE
autogen downloads latest model data every time

### ISSUE THREAD

**Issue by LigH-de** [xiph/opus#319]
When [building opus in the media-autobuild suite](https://github.com/m-ab-s/media-autobuild_suite/issues/2613) (a set of shell scripts which keeps an MSYS2/MinGW environment up to date before compiling ffmpeg and a lot of libraries to be linked in it), the file `opus_data-735117b.tar.gz` gets downloaded every time in both MinGW32 and MinGW64 build scripts. I believe autogen always executes **dnn/download_model.{bat|sh}** without checking the presence of the file to be downloaded, so it gets re-downloaded during every building attempt, despite its existence on the local harddisk.

[ab-suite.autogen.log](https://github.com/xiph/opus/files/14501573/ab-suite.autogen.log)

**Comment by jmvalin** [comment]
The download_model.sh script does a check and only downloads the model if it's not already there. It does untar the model every time though in case someone/something overwrote it.

**Comment by LigH-de** [comment]
OK, m-ab-s maintainers check why it happens there.
