### ISSUE TITLE
opus 1.5.1-1 seems to be incompatible with musescore 4.2.1

### ISSUE THREAD

**Issue by NeroBlackstone** [xiph/opus#324]
Judging from the context of this [issue](https://github.com/musescore/MuseScore/issues/21838), it should be an Opus problem.

**Comment by jmvalin** [comment]
See my comment on that musescore issue. The assert that fails was added specifically to catch cases where the decoder state is getting corrupted by some other piece of code. So the issue is very likely a bug in musescore rather than one in Opus.
