### ISSUE TITLE
Error: Range coder state mismatch between encoder and decoder in frame 1: 0x f3b1240 vs 0x40123b0f

### ISSUE THREAD

**Issue by chenyangMl** [xiph/opus#341]
1. Run command
 ```
 ./opus_demo -d 16000 1 test.opus test.pcm
 ```

2.  error log
libopus 1.5.2
Decoding with 16000 Hz output (1 channels)
Error: Range coder state mismatch between encoder and decoder in frame 1: 0x f3b1240 vs 0x40123b0f

I don not known how to debug this problem.  Can you give me some advise ?

**Comment by jmvalin** [comment]
opus_demo cannot decode Ogg Opus files. It can only decode files that were encoded with opus_demo.
