### ISSUE TITLE
Possible problem in silk/MacroCount.h

### ISSUE THREAD

**Issue by petrufm** [xiph/opus#35]
In the file silk/MacroCount.h line 694, shouldn't the return type of the silk_LIMIT_32 function be "opus_int32" instead of "opus_int"? All parameters and the variable used to compute the return value are declared as "opus_int32". Moreover, in the case of other functions from the same file, there is a consistency between these types and the return type of the corresponding functions. I detected this automatically using a CodeSonar plugin.

**Comment by jmvalin** [comment]
Thanks for reporting this. Just landed the fix.
