### ISSUE TITLE
Flush encoder before a restarting the stream

### ISSUE THREAD

**Issue by goatchurchprime** [xiph/opus#381]
This is similar to #148 but from the front end where I want to restart the stream of calls to `opus_encode_float()` after skipping a number of frames.  I'm using the volume threshold in the microphone to turn on and off the encoding so that it's not wasting CPU cycles during most of the time when the person is not talking. 

If I ignore the problem I get a very small bit of run-on from the previous sound from before I stopped sending audio chunks to the opus encoder.  It gets better if I send 5 blank frames into the encoder before using it again, but there has to be a better (more proper) way to flush its state and reset it to as if I had deleted and constructed the OpusEncoder again.

**Comment by xnorpx** [comment]
Why not use DTX? 

https://opus-codec.org/docs/opus_api-1.5/group__opus__encoderctls.html#ga4f053b2db8c5162293213aabfe123773

**Comment by goatchurchprime** [comment]
It's not quite what I want. 

DTX lets the Opus library decide when there are periods of silence in the audio stream and then automatically drops into a different state.  

However I am controlling the periods of silence and transmission outside the library, for example with a Push-To-Talk (PTT) button and I would like to reset the encoder back to the state it was created in.

The function I am looking for is present in the speex_resampler here:
  https://github.com/xiph/speexdsp/blob/master/include/speex/speex_resampler.h#L328

**Comment by goatchurchprime** [comment]
Found it.  There's a comment here: https://github.com/xiph/opus/blob/main/include/opus.h#L219
> To reset a previously initialized state, use the #OPUS_RESET_STATE CTL.

So the function I need to call is:
> opus_encoder_ctl(opusencoder, OPUS_RESET_STATE);
