### ISSUE TITLE
Failure with autogen on master with Ubuntu

### ISSUE THREAD

**Issue by mondain** [xiph/opus#40]
On Ubuntu 16.04 with fresh clone, I see this error and not being a C developer I don't know how to address it.
```sh
opus$ ./autogen.sh
Updating build configuration files, please wait....
configure.ac:38: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:38: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by rillian** [comment]
This means you're missing some of the development environment required to compile the package. Try `sudo apt-get install libtool`. As a short-cut to get everything you'll need, you can also try `sudo apt-get builddep libopus`.

Hope that helps.

**Comment by rillian** [comment]
Hmm, the `build-dep` command isn't work for me in xenial. Something like this should work to set up the necessary build environment:
```
sudo apt-get install git autoconf automake libtool make gcc
```

**Comment by mondain** [comment]
Its especially odd considering that I can build opus.1.1.4 from the released tarball as well as ffmpeg 3.1.6, but cannot build from source here. What lead me to attempt building libopus from the git repo is that I cannot get ffmpeg to find libopus for encoding (works fine for decode). I'm just exploring avenues to find out whats the matter. Also on the matter of ffmpeg I am using the proper flags:  `--enable-libopus --enable-decoder=libopus --enable-encoder=libopus`

**Comment by gcp** [comment]
>Its especially odd considering that I can build opus.1.1.4 from the released tarball as well as ffmpeg 3.1.6, but cannot build from source here.

This is an expected result, because the tarball contains the pre-generated autoconf/libtool scripts, and the source does not. (This is the same for like >90% of all open source Unix software out there)

**Comment by mondain** [comment]
@gcp thanks for that info; again I'm not a c/c++ guy so please be kind :)  It does however seem that I should be able to follow the readme here in the repo and be able to produce usable output.

**Comment by gcp** [comment]
The README explicitly addresses the difference (running ./autogen.sh). Unfortunately installing the missing dependencies to get that to work is a rather distribution specific step.

I'm just explaining why you get a different result between tarballs and the git repo - it's not a bug.

**Comment by mondain** [comment]
Am I wrong to assume said dependencies should be listed?

**Comment by gcp** [comment]
They're named and packaged differently in every Linux distribution.

**Comment by mondain** [comment]
@rillian I'm using non-sudo make install as I'm building into a `prefix` directory and I am not trying to install to my local system. Also libopus is listed after configure in ffmpeg as an encoder and decoder. Lastly, yes everything is built into prefix:  ```
libopus.a
libopus.la
libopus.so
libopus.so.0
libopus.so.0.5.4
```
Didn't list all the libs for ff.

**Comment by mondain** [comment]
@gcp how is listing something like `libogg` if its a dep for `libopus` an issue of os type? Right now, I know of no deps whatsoever.

**Comment by rillian** [comment]
Ok, this is an ffmpeg question. Probably it doesn't know to look in the `prefix` for libopus. Try setting PKG_CONFIG_PATH=$prefix/lib/pkg-config, maybe?

**Comment by mondain** [comment]
Actually I have that in the `env` already. ```PKG_CONFIG_PATH=/home/mondain/workspace/ext/ffmpeg-3.1.6/ffmpeg_build/lib/pkgconfig```

**Comment by mondain** [comment]
I believe `libopenh264` required it.

**Comment by rillian** [comment]
ffmpeg's configure has a --pkgconfigdir option. It's supposed to default to `prefix`, but maybe it would help.

**Comment by mondain** [comment]
Had I gotten past the autogen issue, my build command for libopus would have been:
```
./configure --prefix="${BUILD_HOME}/ffmpeg_build" --enable-shared --enable-dependency-tracking --enable-float-approx --disable-doc --disable-extra-programs --with-pic
make && make install
```

**Comment by mondain** [comment]
@rillian I shall give that a go, thank you.

**Comment by mondain** [comment]
Everything built with that additional parameter, but the result is still the same, the libopus encoder link is broken. Thanks for your help guys.

**Comment by rillian** [comment]
I've added documentation about installing build dependencies in badd1e56c64a4af8138c542c2a0507f3c8cca1d9. Thanks for pointing out the issue!

As for getting your build to work, I think you'll have to find someone more familiar with ffmpeg to help. I've only used it with the default install locations.
