### ISSUE TITLE
/tmp/ccOBaCHb.s:281: Error: first destination register must be even -- `ldrd r5,r6,[lr,fp]'

### ISSUE THREAD

**Issue by doujanbo** [xiph/opus#49]
root@dou-pc:~/opus# make
./celt/arm/arm2gnu.pl  < celt/arm/armopts.s > celt/arm/armopts-gnu.S
./celt/arm/arm2gnu.pl  < celt/arm/celt_pitch_xcorr_arm.s > celt/arm/celt_pitch_xcorr_arm-gnu.S
make  all-recursive
make[1]: Entering directory `/root/opus'
make[2]: Entering directory `/root/opus'
  CC       celt/bands.lo
  CC       celt/celt.lo
  CC       celt/celt_encoder.lo
  CC       celt/celt_decoder.lo
  CC       celt/cwrs.lo
  CC       celt/entcode.lo
  CC       celt/entdec.lo
  CC       celt/entenc.lo
  CC       celt/kiss_fft.lo
/tmp/ccOBaCHb.s: Assembler messages:
/tmp/ccOBaCHb.s:281: Error: first destination register must be even -- `ldrd r5,r6,[lr,fp]'
/tmp/ccOBaCHb.s:292: Error: first destination register must be even -- `ldrd r5,r6,[r9,fp]'
make[2]: *** [celt/kiss_fft.lo] Error 1
make[2]: Leaving directory `/root/opus'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/opus'
make: *** [all] Error 2

**Comment by rillian** [comment]
Hi! Thanks for the report. What target and configure options did you use?

**Comment by doujanbo** [comment]
I can't speak English very much. Thank you very much for your reply!
Here is my compilation information

root@dou-pc:~/opus-1.1# ./configure --host=arm-linux --enable-fixed-point
--prefix=$PWD/tmp
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-strip... arm-linux-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... i686-pc-linux-gnu
checking host system type... arm-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for arm-linux-gcc... arm-linux-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-gcc accepts -g... yes
checking for arm-linux-gcc option to accept ISO C89... none needed
checking dependency style of arm-linux-gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by arm-linux-gcc...
/usr/local/arm_linux_4.2/arm-none-linux-gnueabi/bin/ld
checking if the linker
(/usr/local/arm_linux_4.2/arm-none-linux-gnueabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)...
/usr/local/arm_linux_4.2/bin//arm-linux-nm -B
checking the name lister (/usr/local/arm_linux_4.2/bin//arm-linux-nm -B)
interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to
arm-unknown-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format...
func_convert_file_noop
checking for /usr/local/arm_linux_4.2/arm-none-linux-gnueabi/bin/ld option
to reload object files... -r
checking for arm-linux-objdump... arm-linux-objdump
checking how to recognize dependent libraries... pass_all
checking for arm-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-ar... arm-linux-ar
checking for archiver @FILE support... @
checking for arm-linux-strip... (cached) arm-linux-strip
checking for arm-linux-ranlib... arm-linux-ranlib
checking command to parse /usr/local/arm_linux_4.2/bin//arm-linux-nm -B
output from arm-linux-gcc object... ok
checking for sysroot... no
checking for arm-linux-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... arm-linux-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-linux-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-linux-gcc option to produce PIC... -fPIC -DPIC
checking if arm-linux-gcc PIC flag -fPIC -DPIC works... yes
checking if arm-linux-gcc static flag -static works... yes
checking if arm-linux-gcc supports -c -o file.o... yes
checking if arm-linux-gcc supports -c -o file.o... (cached) yes
checking whether the arm-linux-gcc linker
(/usr/local/arm_linux_4.2/arm-none-linux-gnueabi/bin/ld) supports shared
libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether arm-linux-gcc and cc understand -c and -o together... yes
checking for arm-linux-gcc option to accept ISO C99... -std=gnu99
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking dependency style of arm-linux-gcc -std=gnu99... gcc3
checking for C/C++ restrict keyword... __restrict
checking for C99 variable-size arrays... yes
checking for cos in -lm... yes
checking if compiler supports gcc-style inline assembly... yes
checking if assembler supports EDSP instructions on ARM... yes
checking if assembler supports ARMv6 media instructions on ARM... yes
checking if assembler supports NEON instructions on ARM... no
checking for perl... yes
configure: Trying to force-enable NEON instructions...
checking if assembler supports NEON instructions on ARM... no
checking for doxygen... no
checking if arm-linux-gcc -std=gnu99 supports -fvisibility=hidden... yes
checking if arm-linux-gcc -std=gnu99 supports -Wall -Wextra -Wcast-align
-Wnested-externs -Wshadow -Wstrict-prototypes... yes
checking for lrintf... yes
checking for lrint... yes
checking for __malloc_hook... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating opus.pc
config.status: creating opus-uninstalled.pc
config.status: creating celt/arm/armopts.s
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
-------------------------------------------------- ----------------------
  opus 1.1: Automatic configuration OK.

    Compiler support:

      C99 var arrays: ................ yes
      C99 lrintf: .................... yes
      Use alloca: .................... no (using var arrays)

    General configuration:

      Floating point support: ........ no
      Fast float approximations: ..... no
      Fixed point debugging: ......... no
      Inline Assembly Optimizations: . ARM (EDSP) (Media)
      External Assembly Optimizations: ARM (EDSP) (Media)
      Run-time CPU detection: ........ no
      Custom modes: .................. no
      Assertion checking: ............ no
      Fuzzing: ....................... no

      API documentation: ............. yes
      Extra programs: ................ yes
-------------------------------------------------- ----------------------

 Type "make; make install" to compile and install
 Type "make check" to run the test suite

root@dou-pc:~/opus-1.1#
root@dou-pc:~/opus-1.1#
root@dou-pc:~/opus-1.1# make
./celt/arm/arm2gnu.pl < celt/arm/armopts.s > celt/arm/armopts-gnu.S
./celt/arm/arm2gnu.pl < celt/arm/celt_pitch_xcorr_arm.s >
celt/arm/celt_pitch_xcorr_arm-gnu.S
make all-recursive
make[1]: Entering directory `/root/opus-1.1'
make[2]: Entering directory `/root/opus-1.1'
  CC celt/kiss_fft.lo
/tmp/ccmbyj4g.s: Assembler messages:
/tmp/ccmbyj4g.s:691: Error: first destination register must be even --
`ldrd r7,r8,[sl,#0]'
/tmp/ccmbyj4g.s:719: Error: first destination register must be even --
`ldrd r7,r8,[sl,#0]'
/tmp/ccmbyj4g.s:736: Error: first destination register must be even --
`ldrd r7,r8,[fp,#0]'
/tmp/ccmbyj4g.s:1442: Error: first destination register must be even --
`ldrd r7,r8,[r9,#0]'
/tmp/ccmbyj4g.s:3345: Error: first destination register must be even --
`ldrd r5,r6,[r3,r7]'
make[2]: *** [celt​​/kiss_fft.lo] Error 1
make[2]: Leaving directory `/root/opus-1.1'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/opus-1.1'
make: *** [all] Error 2

2017-06-22 13:27 GMT+08:00 Ralph Giles <notifications@github.com>:

**Comment by doujanbo** [comment]
root@dou-pc:~/opus-1.1# arm-linux-gcc -v
Using built-in specs.
Target: arm-none-linux-gnueabi
Configured with: ../../gcc-4.2.1/configure --prefix=/usr/local/arm_linux_4.2 --target=arm-none-linux-gnueabi --enable-languages=c,c++ --with-gnu-ld --with-gnu-as --disable-nls --with-float=soft --without-newlib --disable-libmudflap --disable-libssp --disable-libgomp
Thread model: posix
gcc version 4.2.1

**Comment by doujanbo** [comment]
root@dou-pc:~/opus-1.1# uname --all
Linux dou-pc 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by doujanbo** [comment]
The problem was solved. It turned out to be too low for my compiler version

**Comment by rillian** [comment]
Glad you got it working.

Also you may try https://archive.mozilla.org/pub/opus/opus-1.2.tar.gz

**Comment by doujanbo** [comment]
OK!
