### ISSUE TITLE
Suggestion: Move test/demo application sources to a separate folder

### ISSUE THREAD

**Issue by GregSlazinski** [xiph/opus#52]
There are a few files that are applications, and I would recommend moving them to a separate folder, outside of the library folder:
src/opus_compare.c
src/repacketizer_demo.c

It will be more clean if library and demo apps are in separate folders.

**Comment by jmvalin** [comment]
I'm not sure that it makes much of a difference, so to me it's not worth the trouble of updating all the build files (and for sure forgetting something and breaking things).
