### ISSUE TITLE
question... quality comparison between Opus 256 and 512

### ISSUE THREAD

**Issue by Sa-Ja-Di** [xiph/opus#56]
Regarding that post here:

https://www.reddit.com/r/audiophile/comments/40g900/flac_vs_lossy_compression_opusaacmp3_etc/

Is said that Opus 512 takes more underlying song elements away as compared to lower bitrates.

This link leads here - where a comparison was done about the elements which Opus and other audio codecs remove (Listen to the 256 and 512 Opus samples)

https://soundcloud.com/kingo64-1/sets/lossy-audio-compression-comparisons

So, is it normal that 512 strips away more minor parts than 256?

**Comment by tdaede** [comment]
Subtracting the compressed and original audio isn't useful to compare audio codecs for many reasons. As an example of one reason, Opus (and all good encoders) take advantage of masking - a psychoacoustic property where loud sounds hide quiet sounds. If you subtract the two, you lose this property.

A much better methodology is the one done by this test, for example: http://listening-test.coresv.net/index.htm

And the results: http://listening-test.coresv.net/results.htm

For very high rates, you can also do a much simpler ABX test, which just tells you whether you can hear a difference or not.

You might also be interested in the HydrogenAudio listening test forum: https://hydrogenaud.io/index.php/board,40.0.html
