### ISSUE TITLE
Compilation Error - celt/arm/{fft_arm.h, mdct_arm.h} include config.h unconditionally

### ISSUE THREAD

**Issue by Brahmasmi** [xiph/opus#6]
Compiling opus for the armv7 architecture for Android outputs

```
[armeabi-v7a] Compile arm    : opus <= opus_multistream.c
In file included from ./libopus/celt/kiss_fft.h:100:0,
                 from ./libopus/celt/mdct.h:46,
                 from ./libopus/celt/modes.h:36,
                 from ./libopus/src/opus_decoder.c:44:
./libopus/celt/arm/fft_arm.h:37:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
```

There is no config.h in the opus sources, except one in the win32 directory which is not applicable for the current build. The offending line is this

```

#include "config.h"
```

(https://github.com/xiph/opus/blob/master/celt/arm/fft_arm.h#L36-L37)

Both fft_arm.h and mdct_arm.h have the same config block, and subsequently the same error.

Should we be checking HAVE_CONFIG_H before including the config.h, similar to the check in other files?

**Comment by coltongit** [comment]
Maybe adding the config.h to the source code will solve this issue, Brahmasmi.

**Comment by coltongit** [comment]
Actually making a config.h for this version might be able to solve the compile issue.

**Comment by Brahmasmi** [comment]
Unfortunately, I do not know whether creating a config.h is the solution, and if it is, what should be the contents of the file.

I assumed that the files (celt/arm/{fft_arm.h, mdct_arm.h}) are missing a HAVE_CONFIG_H check. I based this assumption on similar checks across the code base. As an example, in https://github.com/xiph/opus/blob/master/src/opus_encoder.c#L28-L30.
```
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
```

**Comment by coltongit** [comment]
Then it should (most likely) be put in, & see if that fixes these errors.

**Comment by jmvalin** [comment]
Two things here:
1) The #include "config.h"  should always be within an #ifdef HAVE_CONFIG_H 
2) We should never include config.h from a header file
So we'll have to fix both, but it might take some time since I need to have a setup to make sure I don't break anything in the process.

**Comment by coltongit** [comment]
Hopefully that happens soon.

**Comment by mark4o** [comment]
Fixed by mjbshaw in 4911460353b37000f5d928b75707acb14e7b2855.

**Comment by coltongit** [comment]
If this is already fixed, shouldn't it be tested first before this gets closed?

**Comment by jmvalin** [comment]
Feel free to reopen if problems remain
