### ISSUE TITLE
Opus goes into DTX one frame too early in Silk mode.

### ISSUE THREAD

**Issue by gustafullberg** [xiph/opus#72]
If DTX is enabled, the Opus codec goes into DTX after 10 frames of inactivity, and then stays in DTX for 20 frames before coding the noise and sending a new frame.

In Silk only mode, DTX is entered after 9 frames of inactivity, and DTX is maintained for 21 frames before coding a new frame.

The behaviour of DTX should not differ depending on modes, and the latter behaviour does not match the macros in define.h:

```
/* DTX settings */
#define NB_SPEECH_FRAMES_BEFORE_DTX             10      /* eq 200 ms */
#define MAX_CONSECUTIVE_DTX                     20      /* eq 400 ms */
```

**Comment by jmvalin** [comment]
merged the corresponding pull request
