### ISSUE TITLE
UBSan: src/opus_demo.c:875:49: runtime error: division by zero

### ISSUE THREAD

**Issue by tysmith** [xiph/opus#76]
src/opus_demo.c:875:49: runtime error: division by zero
    #0 0x42a451 in main /home/user/code/opus/src/opus_demo.c:875:49
    #1 0x7ffbb460d82f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #2 0x402de8 in _start (/home/user/code/opus/opus_demo+0x402de8)

**Comment by tysmith** [comment]
[testcase.bit.zip](https://github.com/xiph/opus/files/1560955/testcase.bit.zip)

**Comment by jmvalin** [comment]
Fixed
