### ISSUE TITLE
PLC generating silence?

### ISSUE THREAD

**Issue by ArnaudBienner** [xiph/opus#82]
Hi,

I discovered Opus has a PLC mechanism and wanted to use it.

I tried opus_demo in version 1.2.1 and it doesn't really seem to work.
 
Here is what I do: opus_demo audio 48000 2 70600 -loss 1  input.wav out.wav
Using "voip" instead of "audio" doesn't help.
In any case, I can clearly hear the missing audio (and see silence using audacity).

I tried to debug the demo application and I can clearly see it is passing a NULL pointer but a size > 0 (around opus_demo.c:778), which is what you need to do, according to the documentation.
And that afterwards some processing is taking place which seems related to PLC (e.g. in celt_decode_lost) but I'm not sure what it is actually doing.

Does someone know more about how PLC is working in Opus?
I spend some time looking around but couldn't find useful resources about this.
I suspect it might work or not depending on the audio input, how repetitive it is etc. but would be curious to know the limitations it might have.

In advance, thanks a lot!

Arnaud

**Comment by jmvalin** [comment]
You're seeing pure silence for the missing frames or are you just saying there are artefacts? Also, keep in mind that the PLC tends to work better for speech than music. That being said, it should always do something and not just insert silence.

**Comment by ArnaudBienner** [comment]
@jmvalin I'm seeing pure silence.
I tested with a movie trailer, which contain both music and speech.
If you believe it should work on this case too, I will try to get a short extract to share with you, if you think that can help?

**Comment by jmvalin** [comment]
Yes, please share the following:
1) the input audio file
2) the exact command line you're using
3) the output you're seeing

**Comment by ArnaudBienner** [comment]
Hi,

I've put the files here (source and generated by libopus):
https://drive.google.com/open?id=1Ac5sPuzCLWsEcen8UILFtU7jXykLSPIB

I've generated the .wav from a Blender movie [1] [2] using the following command:
```
ffmpeg -i ToS-4k-1920.mov  ToS-4k-1920.wav
```

Then, with libopus 1.2.1 I've compiled locally on my macOS 10.11:
```
.libs/opus_demo audio 48000 2 128000 ToS-4k-1920.wav ToS_noloss.raw
.libs/opus_demo audio 48000 2 128000 -loss 1 ToS-4k-1920.wav ToS_loss1.raw
```

I've opened the generated files in Audacity using the following settings:
Encoding: Signed 16 bits
Little-endian
Stereo
Sample Rate: 44100 Hz; Note: I'm not sure why output is 44100: this was the source sample rate, but I specified 48kHz in the opus_demo command line

Listening to the audio with 1 percent loss, I can regularly hear some silences.
And they are visible in the Audicity, as you can see in this screenshot:
![screenshot_audacity](https://user-images.githubusercontent.com/1533690/38029674-d7f5ea62-3296-11e8-87da-fa0d35c51370.png)


I had the same problem with another wav file, with sample rate 48kHz.

What do you think?

[1]: https://mango.blender.org/download/
[2]: http://ftp.halifax.rwth-aachen.de/blender/demo/movies/ToS/ToS-4k-1920.mov

**Comment by jmvalin** [comment]
Can you check if master still has the problem? There was a PLC bug in 1.2

**Comment by ArnaudBienner** [comment]
That seems better: I can hear some artifact (not always) but at least it's not just silence.
I guess PLC can't compensate for all packets loss.
