### ISSUE TITLE
Provide CMake Build Support

### ISSUE THREAD

**Issue by ghost** [xiph/opus#85]
Hello,

It would be extremely helpful if the project could be built via CMake. As it is the project can be built under Cygwin or MSYS2, but these environments are not always available. The VS2015 project is thoughtful but MSVC produced libraries sometimes do not work with other compilers (mainly MinGW[-w64]).

I understand this may be some work.

Cheers,
     R0b0t1

**Comment by Zingam** [comment]
As this codec will most probably be commonly used with the new AV1 which supports CMake builds it would make sense to add CMake support to Opus. Here is some example support: 
https://github.com/rtaudio/opus-cmake/blob/master/CMakeLists.txt
It looks that it wouldn't be too difficult to implement.

@R030t1 You should change the title to "Provide CMake build support"

**Comment by berkus** [comment]
See https://github.com/xiph/opus/pull/100

**Comment by jmvalin** [comment]
Closing this, since the discussion is happening in PR #100
