### ISSUE TITLE
Fix memory leaks due to early returns in opus_compare.c and opus_demo.c

### ISSUE THREAD

**Issue by ddkilzer** [xiph/opus#90]
The clang static analyzer detects memory leaks due to early returns in opus_compare.c and opus_demo.c.

More info in this bug and patch from the WebKit project:
https://bugs.webkit.org/show_bug.cgi?id=186009
https://trac.webkit.org/changeset/232236

**Comment by jmvalin** [comment]
We're aware of the opus_compare.c issue and it's a WONTFIX. That file is part of the standard for testing Opus compliance so we're not changing it at all unless something really bad gets discovered. When it comes to opus_demo, it would be good to have a less repetitive patch (maybe using goto?) to merge.

**Comment by ddkilzer** [comment]
Seems odd to leave known issues unfixed in test code, but okay.

I’m not allowed to post patches to other projects without internal review, so this bug report documents the issue.  You’re free to take the existing patch and use it, modify it or fix it a different way.  I’m not a huge fan of goto statements, anyway.  :)

**Comment by jmvalin** [comment]
About opus_compare.c, let's just say that it's as much of a contract and political statement as it is software, so any change to it makes some people nervous. As for opus_demo.c, can you have a look at this goto-based patch I made and give it a try?
 https://jmvalin.ca/misc_stuff/fix_opus_demo_leaks.patch
As much as I also hate gotos in general, I think this is the one use case, where it's cleaner than alternatives. I believe it also addresses a case that your patch missed (exiting on opus_decoder_create() would fail to destroy the encoder)
