### ISSUE TITLE
Max amount of previous packets/blocks for seeking

### ISSUE THREAD

**Issue by GregSlazinski** [xiph/opus#96]
The opus header file states:

>   * Opus is a stateful codec with overlapping blocks and as a result Opus
>   * packets are not coded independently of each other. Packets must be
>   * passed into the decoder serially and in the correct order for a correct
>   * decode.

What is the max amount of blocks do I need to process first when seeking?

Example if I want to start playback from frame/packet/block #200, how many packets should I process first?
I've done some tests and the smallest number of extra packets I have to process first is 32, is that correct? so starting packet for decoding would be from 200-32?
and it looks like OPUS_RESET_STATE is also needed before processing the packets, which I'm using.

Edit: after further tests, to get bit-exact results I get 32 packets instead of 31.

**Comment by jmvalin** [comment]
31 frames sounds like a lot, unless they're really short. I would say 80 ms (4 frames of 20 ms) should be enough to get something that *sounds* right (even if the signal is not exactly the same).

**Comment by GregSlazinski** [comment]
Thanks for reply, after further tests the value is 32, not 31, so I've updated my first post. Actually I'm interested in bit-exact results, so that the output will always be the same no matter if played from the start to desired position, or by seeking.

For those tests I'm using my own file format container that stores raw opus frames. And only by decoding 32 frames before target I get exactly the same results.

BTW. I've noticed that https://github.com/xiph/opusfile does not produce bit-exact results when using 'op_pcm_seek'
Is there any way to force bit-exact results for OpusFile?
For OpusFile I'm using 'op_pcm_seek' and 'op_read_stereo'

**Comment by jmvalin** [comment]
Opus is not a "bit-exact" codec. Even without the seeking issue, different build options are likely to give you slightly different results. Floating-point builds will differ from fixed-point builds, and even within the float builds, different compiler options may change the result slightly. The quality will still be exactly the same, but the values won't match perfectly.

Back to seeking, there is no theoretical number of frames ahead that will guarantee bit-exact decoding. If you really need that feature (which I kinda doubt), the only way to get it is by disabling prediction (OPUS_SET_PREDICTION_DISABLED) in the encoder, in which case 1-2 frames would be sufficient.

**Comment by GregSlazinski** [comment]
Thank you for your reply.
Does that mean more than 32 frames could be needed in some cases?
For now I'll close the issue as I'm satisfied with the results I've got.

**Comment by jmvalin** [comment]
Depends on your definition of "needed". You need only about 4 to make the seek inaudible. OTOH, no amount is going to guarantee bit-exact decoding. As I pointed out, you can't have bit-exact even without seeking if you're comparing two different builds.

**Comment by GregSlazinski** [comment]
I'm not talking about different builds, I'm talking about the same application, running on the same computer, but one time decoding from the start of the stream, and another time with seeking.

**Comment by jmvalin** [comment]
Then the more frames you go back, the more likely you are to get bit-exact, but there's no number that'll provide a 100% guarantee. And to be honest, if your application requires that, it seems to me like there's something fundamentally wrong with it.
